#!/bin/bash
# build.sh - Build Sage Engine into a distributable binary
#
# Creates a self-contained executable that embeds the engine source
# and launches via a custom C wrapper around the sage interpreter.
#
# Usage: ./build.sh [game_script.sage] [-o output_name]

set -e

SAGE_DIR="$(cd "$(dirname "$0")/../sagelang" && pwd)"
ENGINE_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$ENGINE_DIR/build"

GAME_SCRIPT="${1:-examples/demo_ui.sage}"
OUTPUT_NAME="${3:-sage_engine}"

# Parse -o flag
if [ "$2" = "-o" ] && [ -n "$3" ]; then
    OUTPUT_NAME="$3"
fi

echo "=== Sage Engine Build System ==="
echo "Game script: $GAME_SCRIPT"
echo "Output: $BUILD_DIR/$OUTPUT_NAME"
echo ""

# Create build directory
mkdir -p "$BUILD_DIR"

# ============================================================================
# Step 1: Bundle all engine library modules into one file
# ============================================================================
echo "[1/4] Bundling engine modules..."

BUNDLE="$BUILD_DIR/engine_bundle.sage"
> "$BUNDLE"

# Collect all engine-authored .sage files (not stdlib copies)
ENGINE_MODULES=(
    engine_math ecs events input game_loop components
    render_system lighting sky
    collision physics player_controller gameplay
    asset_manager scene_serial audio
    tween animation navigation behavior_tree
    ui_core ui_renderer hud menu
    terrain water foliage day_night
    particles vfx_presets particle_renderer post_fx
    net_protocol net_server net_client net_replication lobby
    undo_redo inspector gizmo asset_browser scene_editor
)

# Count lines
TOTAL_LINES=0
for mod in "${ENGINE_MODULES[@]}"; do
    if [ -f "$ENGINE_DIR/lib/$mod.sage" ]; then
        lines=$(wc -l < "$ENGINE_DIR/lib/$mod.sage")
        TOTAL_LINES=$((TOTAL_LINES + lines))
    fi
done
echo "  Engine: ${#ENGINE_MODULES[@]} modules, $TOTAL_LINES lines"

# ============================================================================
# Step 2: Generate C wrapper that embeds sage source
# ============================================================================
echo "[2/4] Generating C launcher..."

LAUNCHER_C="$BUILD_DIR/sage_engine_main.c"

cat > "$LAUNCHER_C" << 'CEOF'
/*
 * Sage Engine Launcher
 * Auto-generated by build.sh
 * Finds sage interpreter and runs game scripts from engine directory.
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <libgen.h>
#include <limits.h>

static int try_sage(const char* path, char* out) {
    if (access(path, X_OK) == 0) {
        if (realpath(path, out)) return 1;
    }
    return 0;
}

int main(int argc, char* argv[]) {
    char exe_path[PATH_MAX];
    ssize_t len = readlink("/proc/self/exe", exe_path, sizeof(exe_path) - 1);
    if (len == -1) { perror("readlink"); return 1; }
    exe_path[len] = '\0';

    char exe_dir[PATH_MAX];
    char* tmp = dirname(exe_path);
    if (!realpath(tmp, exe_dir)) strncpy(exe_dir, tmp, PATH_MAX - 1);

    /* chdir to binary's directory (contains lib/, shaders/, examples/) */
    if (chdir(exe_dir) != 0) {
        fprintf(stderr, "Cannot chdir to %s\n", exe_dir);
        return 1;
    }

    /* Find sage binary */
    char sage_path[PATH_MAX], probe[PATH_MAX];
    int found = 0;
    const char* env_sage = getenv("SAGE_PATH");
    if (env_sage && try_sage(env_sage, sage_path)) found = 1;
    if (!found) { snprintf(probe, sizeof(probe), "%s/../../sagelang/sage", exe_dir); if (try_sage(probe, sage_path)) found = 1; }
    if (!found) { snprintf(probe, sizeof(probe), "%s/../../../sagelang/sage", exe_dir); if (try_sage(probe, sage_path)) found = 1; }
    if (!found) { snprintf(probe, sizeof(probe), "%s/../sagelang/sage", exe_dir); if (try_sage(probe, sage_path)) found = 1; }
    if (!found) {
        fprintf(stderr, "Cannot find sage binary. Set SAGE_PATH env var.\n");
        return 1;
    }

    const char* script = (argc > 1) ? argv[1] : SAGE_ENGINE_DEFAULT_SCRIPT;
    char* sa[64]; int ai = 0;
    sa[ai++] = sage_path;
    sa[ai++] = (char*)script;
    for (int i = 2; i < argc && ai < 63; i++) sa[ai++] = argv[i];
    sa[ai] = NULL;
    execv(sage_path, sa);
    perror("execv"); return 1;
}
CEOF

# Inject the default script path
sed -i "s|SAGE_ENGINE_DEFAULT_SCRIPT|\"$GAME_SCRIPT\"|" "$LAUNCHER_C"

# ============================================================================
# Step 3: Compile C launcher
# ============================================================================
echo "[3/4] Compiling launcher..."

gcc -O2 -o "$BUILD_DIR/$OUTPUT_NAME" "$LAUNCHER_C"
echo "  Binary: $BUILD_DIR/$OUTPUT_NAME ($(stat -c%s "$BUILD_DIR/$OUTPUT_NAME") bytes)"

# ============================================================================
# Step 4: Create distributable package
# ============================================================================
echo "[4/4] Creating distribution package..."

DIST_DIR="$BUILD_DIR/dist"
rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR/lib" "$DIST_DIR/shaders" "$DIST_DIR/assets" "$DIST_DIR/examples"

# Copy binary
cp "$BUILD_DIR/$OUTPUT_NAME" "$DIST_DIR/"

# Copy engine libraries
for mod in "${ENGINE_MODULES[@]}"; do
    if [ -f "$ENGINE_DIR/lib/$mod.sage" ]; then
        cp "$ENGINE_DIR/lib/$mod.sage" "$DIST_DIR/lib/"
    fi
done

# Copy stdlib modules (needed at runtime)
for f in "$ENGINE_DIR"/lib/*.sage; do
    base=$(basename "$f")
    if [ ! -f "$DIST_DIR/lib/$base" ]; then
        cp "$f" "$DIST_DIR/lib/"
    fi
done

# Copy shaders
cp "$ENGINE_DIR"/shaders/*.spv "$DIST_DIR/shaders/" 2>/dev/null || true
cp "$ENGINE_DIR"/shaders/*.vert "$DIST_DIR/shaders/" 2>/dev/null || true
cp "$ENGINE_DIR"/shaders/*.frag "$DIST_DIR/shaders/" 2>/dev/null || true

# Copy examples
cp "$ENGINE_DIR"/examples/*.sage "$DIST_DIR/examples/" 2>/dev/null || true

# Copy assets
cp "$ENGINE_DIR"/assets/* "$DIST_DIR/assets/" 2>/dev/null || true

# Copy run script
cp "$ENGINE_DIR/run.sh" "$DIST_DIR/"

# Create launcher script (portable fallback)
cat > "$DIST_DIR/launch.sh" << 'EOF'
#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
SAGE="$DIR/../sagelang/sage"
if [ ! -f "$SAGE" ]; then
    echo "Error: sage binary not found at $SAGE"
    echo "Set SAGE_PATH or place sagelang/ alongside the engine directory"
    exit 1
fi
cd "$DIR"
exec "$SAGE" "${1:-examples/demo_ui.sage}" "${@:2}"
EOF
chmod +x "$DIST_DIR/launch.sh"

# Summary
echo ""
echo "=== Build Complete ==="
ENGINE_COUNT=$(ls "$DIST_DIR"/lib/*.sage 2>/dev/null | wc -l)
SHADER_COUNT=$(ls "$DIST_DIR"/shaders/*.spv 2>/dev/null | wc -l)
EXAMPLE_COUNT=$(ls "$DIST_DIR"/examples/*.sage 2>/dev/null | wc -l)
DIST_SIZE=$(du -sh "$DIST_DIR" | cut -f1)
echo "  Distribution: $DIST_DIR ($DIST_SIZE)"
echo "  Binary:       $OUTPUT_NAME"
echo "  Modules:      $ENGINE_COUNT .sage files"
echo "  Shaders:      $SHADER_COUNT .spv files"
echo "  Examples:     $EXAMPLE_COUNT demos"
echo ""
echo "Run: $DIST_DIR/$OUTPUT_NAME [script.sage]"
echo "  or: $DIST_DIR/launch.sh [script.sage]"
