# test_gltf_import.sage - Sanity checks for glTF importer (parsing only)
import io
import math
from gltf_import import load_gltf, create_gltf_result, _decode_accessor_component

let p = 0
let f = 0
proc check(n, c):
    if c:
        p = p + 1
    else:
        print "  FAIL: " + n
        f = f + 1

print "=== glTF Import Sanity Checks ==="

# --- Result structure ---
let r = create_gltf_result()
check("result created", r != nil)
check("meshes empty", len(r["meshes"]) == 0)
check("materials empty", len(r["materials"]) == 0)
check("animations empty", len(r["animations"]) == 0)
check("skins empty", len(r["skins"]) == 0)

# --- Parse minimal glTF JSON ---
from json import cJSON_CreateObject, cJSON_CreateArray, cJSON_CreateNumber, cJSON_CreateString
from json import cJSON_AddItemToObject, cJSON_AddItemToArray, cJSON_AddNumberToObject, cJSON_AddStringToObject
from json import cJSON_Print, cJSON_Delete

let root = cJSON_CreateObject()
let asset = cJSON_CreateObject()
cJSON_AddStringToObject(asset, "version", "2.0")
cJSON_AddStringToObject(asset, "generator", "TestGen")
cJSON_AddItemToObject(root, "asset", asset)
let meshes_arr = cJSON_CreateArray()
let mesh_obj = cJSON_CreateObject()
cJSON_AddStringToObject(mesh_obj, "name", "Cube")
let prims_arr = cJSON_CreateArray()
let prim_obj = cJSON_CreateObject()
cJSON_AddNumberToObject(prim_obj, "material", 0)
cJSON_AddItemToArray(prims_arr, prim_obj)
cJSON_AddItemToObject(mesh_obj, "primitives", prims_arr)
cJSON_AddItemToArray(meshes_arr, mesh_obj)
cJSON_AddItemToObject(root, "meshes", meshes_arr)
let mats_arr = cJSON_CreateArray()
let mat_obj = cJSON_CreateObject()
cJSON_AddStringToObject(mat_obj, "name", "Default")
let pbr_obj = cJSON_CreateObject()
let bcf_arr = cJSON_CreateArray()
cJSON_AddItemToArray(bcf_arr, cJSON_CreateNumber(1.0))
cJSON_AddItemToArray(bcf_arr, cJSON_CreateNumber(0.5))
cJSON_AddItemToArray(bcf_arr, cJSON_CreateNumber(0.2))
cJSON_AddItemToArray(bcf_arr, cJSON_CreateNumber(1.0))
cJSON_AddItemToObject(pbr_obj, "baseColorFactor", bcf_arr)
cJSON_AddNumberToObject(pbr_obj, "metallicFactor", 0.3)
cJSON_AddNumberToObject(pbr_obj, "roughnessFactor", 0.7)
cJSON_AddItemToObject(mat_obj, "pbrMetallicRoughness", pbr_obj)
cJSON_AddItemToArray(mats_arr, mat_obj)
cJSON_AddItemToObject(root, "materials", mats_arr)
let nodes_arr = cJSON_CreateArray()
let node_obj = cJSON_CreateObject()
cJSON_AddStringToObject(node_obj, "name", "CubeNode")
cJSON_AddNumberToObject(node_obj, "mesh", 0)
let trans_arr = cJSON_CreateArray()
cJSON_AddItemToArray(trans_arr, cJSON_CreateNumber(1.0))
cJSON_AddItemToArray(trans_arr, cJSON_CreateNumber(2.0))
cJSON_AddItemToArray(trans_arr, cJSON_CreateNumber(3.0))
cJSON_AddItemToObject(node_obj, "translation", trans_arr)
let rot_arr = cJSON_CreateArray()
cJSON_AddItemToArray(rot_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(rot_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(rot_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(rot_arr, cJSON_CreateNumber(1.0))
cJSON_AddItemToObject(node_obj, "rotation", rot_arr)
let scale_arr = cJSON_CreateArray()
cJSON_AddItemToArray(scale_arr, cJSON_CreateNumber(2.0))
cJSON_AddItemToArray(scale_arr, cJSON_CreateNumber(3.0))
cJSON_AddItemToArray(scale_arr, cJSON_CreateNumber(4.0))
cJSON_AddItemToObject(node_obj, "scale", scale_arr)
let child_arr = cJSON_CreateArray()
cJSON_AddItemToArray(child_arr, cJSON_CreateNumber(1))
cJSON_AddItemToObject(node_obj, "children", child_arr)
cJSON_AddItemToArray(nodes_arr, node_obj)
let child_node_obj = cJSON_CreateObject()
cJSON_AddStringToObject(child_node_obj, "name", "ChildNode")
let matrix_arr = cJSON_CreateArray()
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(1.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(1.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(1.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(4.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(5.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(6.0))
cJSON_AddItemToArray(matrix_arr, cJSON_CreateNumber(1.0))
cJSON_AddItemToObject(child_node_obj, "matrix", matrix_arr)
cJSON_AddItemToArray(nodes_arr, child_node_obj)
cJSON_AddItemToObject(root, "nodes", nodes_arr)
let minimal = cJSON_Print(root)
cJSON_Delete(root)
io.writefile("/tmp/sage_test.gltf", minimal)

let result = load_gltf("/tmp/sage_test.gltf")
check("loaded not nil", result != nil)
if result != nil:
    check("1 mesh", len(result["meshes"]) == 1)
    check("mesh name", result["meshes"][0]["name"] == "Cube")
    check("1 material", len(result["materials"]) == 1)
    check("material name", result["materials"][0]["name"] == "Default")
    check("albedo color r", result["materials"][0]["albedo_color"][0] > 0.9)
    check("albedo color g", result["materials"][0]["albedo_color"][1] > 0.4)
    check("metallic", result["materials"][0]["metallic"] > 0.2)
    check("roughness", result["materials"][0]["roughness"] > 0.6)
    check("2 nodes", len(result["nodes"]) == 2)
    check("node name", result["nodes"][0]["name"] == "CubeNode")
    check("node mesh ref", result["nodes"][0]["mesh"] == 0)
    check("node translation x", result["nodes"][0]["translation"][0] > 0.9)
    check("node rotation stored as quat wxyz", result["nodes"][0]["rotation"][0] > 0.9)
    check("node scale x", result["nodes"][0]["scale"][0] > 1.9)
    check("node child ref", result["nodes"][0]["children"][0] == 1)
    check("child node has matrix", result["nodes"][1]["matrix"][12] > 3.9)

let animated = load_gltf("assets/BoxAnimated.gltf")
check("animated gltf loaded", animated != nil)
if animated != nil:
    check("animated gltf has animations", animated["animation_count"] > 0)
    check("animated gltf channel count", len(animated["animations"][0]["channels"]) > 1)
    check("animated gltf translation channel", animated["animations"][0]["channels"][1]["path"] == "translation")
    check("animated gltf rotation channel", animated["animations"][0]["channels"][0]["path"] == "rotation")
    check("animated gltf duration parsed", animated["animations"][0]["duration"] > 3.7)
    check("animated gltf translation sample parsed", animated["animations"][0]["channels"][1]["values"][1][1] > 2.5)
    let qw = animated["animations"][0]["channels"][0]["values"][0][0]
    check("animated gltf quaternion converted to wxyz", qw > 0.9 or qw < -0.9)

# --- Parse skinned glTF JSON ---
let sk_root = cJSON_CreateObject()
let sk_asset = cJSON_CreateObject()
cJSON_AddStringToObject(sk_asset, "version", "2.0")
cJSON_AddItemToObject(sk_root, "asset", sk_asset)
let sk_nodes = cJSON_CreateArray()
let sk_mesh_node = cJSON_CreateObject()
cJSON_AddStringToObject(sk_mesh_node, "name", "SkinnedMesh")
cJSON_AddNumberToObject(sk_mesh_node, "mesh", 0)
cJSON_AddNumberToObject(sk_mesh_node, "skin", 0)
let sk_mesh_translation = cJSON_CreateArray()
cJSON_AddItemToArray(sk_mesh_translation, cJSON_CreateNumber(5.0))
cJSON_AddItemToArray(sk_mesh_translation, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(sk_mesh_translation, cJSON_CreateNumber(0.0))
cJSON_AddItemToObject(sk_mesh_node, "translation", sk_mesh_translation)
cJSON_AddItemToArray(sk_nodes, sk_mesh_node)
let sk_joint_root = cJSON_CreateObject()
cJSON_AddStringToObject(sk_joint_root, "name", "Hip")
let sk_joint_root_translation = cJSON_CreateArray()
cJSON_AddItemToArray(sk_joint_root_translation, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(sk_joint_root_translation, cJSON_CreateNumber(1.0))
cJSON_AddItemToArray(sk_joint_root_translation, cJSON_CreateNumber(0.0))
cJSON_AddItemToObject(sk_joint_root, "translation", sk_joint_root_translation)
let sk_joint_root_children = cJSON_CreateArray()
cJSON_AddItemToArray(sk_joint_root_children, cJSON_CreateNumber(2))
cJSON_AddItemToObject(sk_joint_root, "children", sk_joint_root_children)
cJSON_AddItemToArray(sk_nodes, sk_joint_root)
let sk_joint_child = cJSON_CreateObject()
cJSON_AddStringToObject(sk_joint_child, "name", "Hand")
let sk_joint_child_translation = cJSON_CreateArray()
cJSON_AddItemToArray(sk_joint_child_translation, cJSON_CreateNumber(0.0))
cJSON_AddItemToArray(sk_joint_child_translation, cJSON_CreateNumber(1.0))
cJSON_AddItemToArray(sk_joint_child_translation, cJSON_CreateNumber(0.0))
cJSON_AddItemToObject(sk_joint_child, "translation", sk_joint_child_translation)
cJSON_AddItemToArray(sk_nodes, sk_joint_child)
cJSON_AddItemToObject(sk_root, "nodes", sk_nodes)
let sk_meshes = cJSON_CreateArray()
let sk_mesh = cJSON_CreateObject()
cJSON_AddStringToObject(sk_mesh, "name", "Body")
let sk_prims = cJSON_CreateArray()
let sk_prim = cJSON_CreateObject()
cJSON_AddItemToArray(sk_prims, sk_prim)
cJSON_AddItemToObject(sk_mesh, "primitives", sk_prims)
cJSON_AddItemToArray(sk_meshes, sk_mesh)
cJSON_AddItemToObject(sk_root, "meshes", sk_meshes)
let sk_skins = cJSON_CreateArray()
let sk_skin = cJSON_CreateObject()
cJSON_AddStringToObject(sk_skin, "name", "Rig")
cJSON_AddNumberToObject(sk_skin, "skeleton", 1)
let sk_joints = cJSON_CreateArray()
cJSON_AddItemToArray(sk_joints, cJSON_CreateNumber(1))
cJSON_AddItemToArray(sk_joints, cJSON_CreateNumber(2))
cJSON_AddItemToObject(sk_skin, "joints", sk_joints)
cJSON_AddItemToArray(sk_skins, sk_skin)
cJSON_AddItemToObject(sk_root, "skins", sk_skins)
let skinned_json = cJSON_Print(sk_root)
cJSON_Delete(sk_root)
io.writefile("/tmp/sage_skinned.gltf", skinned_json)

let skinned = load_gltf("/tmp/sage_skinned.gltf")
check("skinned gltf loaded", skinned != nil)
if skinned != nil:
    check("skinned gltf has skin", skinned["skin_count"] == 1)
    check("skinned gltf node skin ref", skinned["nodes"][0]["skin"] == 0)
    check("skinned gltf skin name", skinned["skins"][0]["name"] == "Rig")
    check("skinned gltf skeleton root", skinned["skins"][0]["skeleton"] == 1)
    check("skinned gltf joint count", skinned["skins"][0]["joint_count"] == 2)
    check("skinned gltf joint name root", skinned["skins"][0]["joint_names"][0] == "Hip")
    check("skinned gltf inverse bind matrices defaulted", len(skinned["skins"][0]["inverse_bind_matrices"]) == 2)
    check("skinned gltf inverse bind identity", skinned["skins"][0]["inverse_bind_matrices"][0][0] > 0.9 and skinned["skins"][0]["inverse_bind_matrices"][0][15] > 0.9)

# --- Accessor component decoding for skinned data ---
check("joint accessor u8 decode", _decode_accessor_component([1], 0, 5121, false) == 1)
let normalized_weight = _decode_accessor_component([128], 0, 5121, true)
check("weight accessor normalized u8 decode", normalized_weight > 0.49 and normalized_weight < 0.51)

# --- Bad file ---
let bad = load_gltf("/tmp/nonexistent.gltf")
check("bad file returns nil", bad == nil)

# --- Invalid JSON ---
io.writefile("/tmp/sage_bad.gltf", "not json at all")
let bad2 = load_gltf("/tmp/sage_bad.gltf")
check("invalid json returns nil", bad2 == nil)

# Cleanup
io.remove("/tmp/sage_test.gltf")
io.remove("/tmp/sage_bad.gltf")
io.remove("/tmp/sage_skinned.gltf")

print ""
print "Results: " + str(p) + " passed, " + str(f) + " failed"
if f > 0:
    raise "glTF import sanity checks failed!"
else:
    print "All glTF import sanity checks passed!"
